This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./ucdavisthesis_main.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file ucdavisthesis_main.acn....done (16 entries accepted, 0 rejected).
Sorting entries....done (55 comparisons).
Generating output file ucdavisthesis_main.acr....done (46 lines written, 0 warnings).
Output written in ucdavisthesis_main.acr.
Transcript written in ucdavisthesis_main.alg.
