SUBROUTINE UserVSCont ( HSS_Spd, GBRatio, NumBl, ZTime, DT, GenEff, DelGenTrq, DirRoot, GenTrq, ElecPwr )

   ! This torque control routine was written by Eric Anderson of UC Davis. The torque control scheme 
   ! is based on the controller described in the NREL 5MW specifications, with the addition of a 
   ! derating scheme described in Eric's dissertation. Derating is achieved by using subroutine 
   ! ControlParameters() to scale relevant control parameters. WARNING: This routine does not include the 
   ! logic required to run linearizations.

USE								precision
USE  							Output
USE								EAControl 	! contains variables: TimeDRStart, TimeDREnd, DerateFactor, TEmShutdown, maxOverspeed, EmergencyShutdown, GenSpeedF, PC_RefSpd, PC_MinPit, VS_Rgn2_K, and VS_RtPwr. See EAControl module in FAST_Mods.f90 for variable descriptions.

IMPLICIT                        NONE

   ! Passed Variables:

INTEGER(4), INTENT(IN )      :: NumBl       ! Number of blades, (-).
REAL(ReKi), INTENT(IN )      :: DelGenTrq   ! Pertubation in generator torque used during FAST linearization (zero otherwise), N-m.
REAL(ReKi), INTENT(IN )      :: DT          ! Integration time step, sec.
REAL(ReKi), INTENT(OUT)      :: ElecPwr     ! Electrical power (account for losses), watts.
REAL(ReKi), INTENT(IN )      :: GBRatio     ! Gearbox ratio, (-).
REAL(ReKi), INTENT(IN )      :: GenEff      ! Generator efficiency, (-).
REAL(ReKi), INTENT(OUT)      :: GenTrq      ! Electrical generator torque, N-m.
REAL(ReKi), INTENT(IN )      :: HSS_Spd     ! HSS speed, rad/s.
REAL(ReKi), INTENT(IN )      :: ZTime       ! Current simulation time, sec.
CHARACTER(1024), INTENT(IN ) :: DirRoot     ! The name of the root file including the full path to the current working directory.  This may be useful if you want this routine to write a permanent record of what it does to be stored with the simulation results: the results should be stored in a file whose name (including path) is generated by appending any suitable extension to DirRoot.

! Local Variables:
REAL(ReKi)                      :: ElapTime      ! Elapsed time since the last call to the controller, sec.
REAL(ReKi), SAVE                :: LastGenTrq    ! Commanded electrical generator torque the last time the controller was called, N-m.
REAL(ReKi), SAVE                :: LastTimeVS    ! Last time the torque controller was called, sec.
REAL(ReKi), PARAMETER           :: OnePlusEps = 1.0 + EPSILON(OnePlusEps)  ! The number slighty greater than unity in single precision.
REAL(ReKi)                      :: TrqRate       ! Torque rate based on the current and last torque commands, N-m/s.
REAL(ReKi), PARAMETER           :: VS_Rgn3MP =  0.01745329 ! Minimum pitch angle at which the torque is computed as if we are in region 3 regardless of the generator speed, rad. -- chosen to be 1.0 degree above PC_MinPit
REAL(ReKi), PARAMETER           :: VS_CtInSp =  70.16224   ! Transitional generator speed (HSS side) between regions 1 and 1 1/2, rad/s.
REAL(ReKi), PARAMETER           :: VS_DT  = 0.00125  ! Communication interval for torque controller, sec.
REAL(ReKi), PARAMETER           :: VS_MaxRat     =   15000.0   ! Maximum torque rate (in absolute value) in torque controller, N-m/s.
REAL(ReKi), PARAMETER           :: VS_MaxTq      =   47402.91  ! Maximum generator torque in Region 3 (HSS side), N-m. -- chosen to be 10% above VS_RtTq = 43.09355kNm
REAL(ReKi), PARAMETER           :: VS_Rgn2Sp     =   91.21091  ! Transitional generator speed (HSS side) between regions 1 1/2 and 2, rad/s.



REAL(ReKi)           			 :: VS_RtGnSp     ! Rated generator speed (HSS side), rad/s. -- cequal to 99% of PC_RefSpd
REAL(ReKi)                		 :: VS_Slope15    ! Torque/speed slope of region 1 1/2 cut-in torque ramp , N-m/(rad/s).
REAL(ReKi)                		 :: VS_Slope25    ! Torque/speed slope of region 2 1/2 induction generator, N-m/(rad/s).
REAL(ReKi), PARAMETER           :: VS_SlPc = 10.0  ! Rated generator slip percentage in Region 2 1/2, %.
REAL(ReKi)                		 :: VS_SySp        ! Synchronous speed of region 2 1/2 induction generator, rad/s.
REAL(ReKi)                		 :: VS_TrGnSp      ! Transitional generator speed (HSS side) between regions 2 and 2 1/2, rad/s.
REAL(ReKi)    					 :: BlPitchCom     ! Commanded blade pitch angle for blade 1 (demand pitch angle), rad.
REAL(ReKi), PARAMETER           :: R2D = 57.295780  ! Factor to convert radians to degrees.

LOGICAL, SAVE					:: Initialize1 = .TRUE.	!Flag used to initialize some saved variables on the first call to this subroutine
LOGICAL, SAVE					:: Initialize2 = .TRUE. !Flag used to initialize some saved variables on the first call to this subroutine

INTEGER(4)       :: TqCount = 1   ! Counter to see how many time subroutine is called

!=======================================================================
   ! Initialize saved variables on first call to subroutine
	IF ( Initialize1 ) THEN
	   WRITE(*,*)  'Running with torque control programmed by Eric Anderson '// &
              'in subroutine UserVSCont(), which can be found in UserSubs.f90 '
	Initialize1 = .FALSE.
		! NOTE: LastGenTrq, though SAVEd, is initialized below for simplicity, not here.
		LastTimeVS = ZTime - VS_DT    ! This will ensure that the torque controller is called on the first pass 
	ENDIF
!=======================================================================
	! Variable-speed torque control:

   ! Compute the elapsed time since the last call to the controller:
   ElapTime = ZTime - LastTimeVS


   ! Only perform the control calculations if the elapsed time is greater than
   !   or equal to the communication interval of the torque controller:
   ! NOTE: Time is scaled by OnePlusEps to ensure that the contoller is called
   !       at every time step when VS_DT = DT, even in the presence of
   !       numerical precision errors.

IF ( ( ZTime*OnePlusEps - LastTimeVS ) >= VS_DT )  THEN

	! Get up to date control parameters
	CALL updateControlParameters( HSS_Spd, ZTime )
	
	IF ( EmergencyShutdown ) THEN
		GenTrq = 0
	ELSE

	   ! Determine some torque control parameters not specified directly:
		VS_RtGnSp = 0.99*PC_RefSpd
		VS_SySp    = VS_RtGnSp/( 1.0 +  0.01*VS_SlPc )
		VS_Slope15 = ( VS_Rgn2_K*VS_Rgn2Sp*VS_Rgn2Sp )/( VS_Rgn2Sp - VS_CtInSp )
		VS_Slope25 = ( VS_RtPwr/VS_RtGnSp           )/( VS_RtGnSp - VS_SySp   )
		VS_TrGnSp = ( VS_Slope25 - SQRT( VS_Slope25*( VS_Slope25 - &
		             4.0*VS_Rgn2_K*VS_SySp ) ) )/( 2.0*VS_Rgn2_K ) !Transition speed from region 2 to region 2.5

		BlPitchCom =  AllOuts(PtchPMzc1)/R2D
	   ! Compute the generator torque, which depends on which region we are in:

		  IF ( (   GenSpeedF >= VS_RtGnSp ) .OR. (  BlPitchCom >= (VS_Rgn3MP + &
		                     PC_MinPit ) ) ) THEN ! We are in region 3 - power is constant
			 GenTrq = VS_RtPwr/GenSpeedF
		  ELSEIF ( GenSpeedF <= VS_CtInSp )  THEN   ! We are in region 1 - torque is zero
			 GenTrq = 0.0
		  ELSEIF ( GenSpeedF <  VS_Rgn2Sp )  THEN   ! We are in region 1 1/2 - linear ramp in torque from zero to optimal
			 GenTrq = VS_Slope15*( GenSpeedF - VS_CtInSp )
		  ELSEIF ( GenSpeedF <  VS_TrGnSp )  THEN           ! We are in region 2 - optimal torque is proportional to the square of the generator speed
			 GenTrq = VS_Rgn2_K*GenSpeedF*GenSpeedF
		  ELSE                                               ! We are in region 2 1/2 - simple induction generator transition region
			 GenTrq = VS_Slope25*( GenSpeedF - VS_SySp   )
		  ENDIF

	   ! Saturate the commanded torque using the maximum torque limit:
		  GenTrq  = MIN( GenTrq                    , VS_MaxTq  )   ! Saturate the command using the maximum torque limit

		!Initialize saved variables on first call to subroutine
		  IF ( Initialize2 ) THEN 
			Initialize2 = .FALSE.
			LastGenTrq = GenTrq                 ! Initialize the value of LastGenTrq on the first pass only
		  ENDIF
	  ENDIF
	  
	! Saturate the commanded torque using the torque rate limit:  
      TrqRate = ( GenTrq - LastGenTrq )/ElapTime               ! Torque rate (unsaturated)
      TrqRate = MIN( MAX( TrqRate, -VS_MaxRat ), VS_MaxRat )   ! Saturate the torque rate using its maximum absolute value
      GenTrq  = LastGenTrq + TrqRate*ElapTime                  ! Saturate the command using the torque rate limit

   ! Reset the values of LastTimeVS and LastGenTrq to the current values:

      LastTimeVS = ZTime
      LastGenTrq = GenTrq

	IF ( controlDebug ) THEN
		WRITE(*,*)  'Time=',ZTime,'TqCount=',TqCount,&
        	      'GenTrq=',GenTrq,'HSS_Spd=',HSS_Spd,'GenSpeedF=',GenSpeedF
    	TqCount = TqCount+1              
	ENDIF

ELSE
	GenTrq = LastGenTrq
ENDIF
   
IF ( GenTrq > 0.0 )  THEN
   ElecPwr = GenTrq*HSS_Spd*GenEff
ELSE
   ElecPwr = GenTrq*HSS_Spd/GenEff
ENDIF

RETURN
END SUBROUTINE UserVSCont